import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";

export default function HowItWorks() {
  return (
    <section id="how-it-works" className="py-20 bg-black text-white">
      <div className="container mx-auto px-4">
        <h2 className="text-4xl font-bold mb-12 text-center bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
          How It Works
        </h2>
        
        <Tabs defaultValue="tell" className="w-full max-w-5xl mx-auto">
          <TabsList className="grid w-full grid-cols-2 md:grid-cols-5 bg-gray-800/50 rounded-xl p-1">
            <TabsTrigger value="tell" className="data-[state=active]:bg-purple-900 data-[state=active]:text-white">TELL Matching</TabsTrigger>
            <TabsTrigger value="mission" className="data-[state=active]:bg-purple-900 data-[state=active]:text-white">Mission Center</TabsTrigger>
            <TabsTrigger value="transfer" className="data-[state=active]:bg-purple-900 data-[state=active]:text-white">Transfer Sessions</TabsTrigger>
            <TabsTrigger value="protocol" className="data-[state=active]:bg-purple-900 data-[state=active]:text-white">Protocol System</TabsTrigger>
            <TabsTrigger value="team" className="data-[state=active]:bg-purple-900 data-[state=active]:text-white">Team Hub</TabsTrigger>
          </TabsList>
          
          <div className="mt-8 bg-gray-900/50 p-6 rounded-xl border border-purple-900/30">
            <TabsContent value="tell" className="space-y-4">
              <h3 className="text-2xl font-semibold text-purple-400">The TELL Matching System</h3>
              <p className="text-gray-300">
                Our Time-Expertise-Learning-Longitude (TELL) Matching System connects you with ideal AI Travelers for your career path. After completing an immersive onboarding experience, the system generates your unique "TELL coordinate" - your position in the career development universe.
              </p>
              <p className="text-gray-300">
                The matching process is visualized as a time-travel experience, where you can see potential AI Travelers from your "future" career path approaching through a virtual timeline. Each AI Traveler represents a different career stage or specialization, with distinct personalities and mentorship approaches based on data from successful professionals.
              </p>
            </TabsContent>
            
            <TabsContent value="mission" className="space-y-4">
              <h3 className="text-2xl font-semibold text-purple-400">Mission Command Center</h3>
              <p className="text-gray-300">
                Transform your career development into an engaging, mission-driven experience. The Mission Command Center presents you with a visually dynamic dashboard organized around your personalized "Grand Plan" - a strategic career roadmap generated by our Director AI.
              </p>
              <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Briefing Phase</h4>
                  <p className="text-sm text-gray-400">Receive mission objectives, required skills, and potential challenges</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Planning Phase</h4>
                  <p className="text-sm text-gray-400">Break down the mission into actionable steps with AI guidance</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Execution Phase</h4>
                  <p className="text-sm text-gray-400">Complete real-world tasks with ongoing AI support</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Debriefing Phase</h4>
                  <p className="text-sm text-gray-400">Analyze outcomes and adjust future mission parameters</p>
                </div>
              </div>
            </TabsContent>
            
            <TabsContent value="transfer" className="space-y-4">
              <h3 className="text-2xl font-semibold text-purple-400">Consciousness Transfer Sessions</h3>
              <p className="text-gray-300">
                Experience immersive knowledge transfer with AI personas through our Consciousness Transfer Sessions. These combine conversational AI, interactive visualization tools, and personalized knowledge synthesis to create meaningful exchanges.
              </p>
              <p className="text-gray-300">
                After each session, the system generates a "Consciousness Fragment" - a multimedia package containing session highlights, key learnings, resources, and actionable next steps that accumulate in your personal knowledge repository.
              </p>
            </TabsContent>
            
            <TabsContent value="protocol" className="space-y-4">
              <h3 className="text-2xl font-semibold text-purple-400">Protocol Guidance System</h3>
              <p className="text-gray-300">
                Navigate professional relationships, career decisions, and workplace challenges through our Protocol Guidance System, which embeds structured rules and ethical frameworks into your career development.
              </p>
              <ul className="mt-4 space-y-2">
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold">1:</span>
                  <div>
                    <span className="font-medium text-purple-300">The Mission Comes First</span>
                    <p className="text-sm text-gray-400">Prioritize career goals aligned with long-term objectives</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold">2:</span>
                  <div>
                    <span className="font-medium text-purple-300">Leave the Future in the Past</span>
                    <p className="text-sm text-gray-400">Apply knowledge appropriately without unrealistic expectations</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold">3:</span>
                  <div>
                    <span className="font-medium text-purple-300">Do No Harm</span>
                    <p className="text-sm text-gray-400">Navigate workplace relationships and conflicts ethically</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold">4:</span>
                  <div>
                    <span className="font-medium text-purple-300">Maintain Your Cover</span>
                    <p className="text-sm text-gray-400">Balance ambition with current workplace realities</p>
                  </div>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold">5:</span>
                  <div>
                    <span className="font-medium text-purple-300">In the Absence of Direction, Maintain the Grand Plan</span>
                    <p className="text-sm text-gray-400">Stay focused during periods between formal guidance</p>
                  </div>
                </li>
              </ul>
            </TabsContent>
            
            <TabsContent value="team" className="space-y-4">
              <h3 className="text-2xl font-semibold text-purple-400">Traveler Team Hub</h3>
              <p className="text-gray-300">
                Experience collaborative team mentorship with diverse AI personas, each bringing specialized expertise to support different aspects of your career development.
              </p>
              <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Team Leader</h4>
                  <p className="text-sm text-gray-400">Provides strategic career guidance and coordinates the team's efforts</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Technical Specialist</h4>
                  <p className="text-sm text-gray-400">Focuses on hard skills and domain expertise</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Workplace Navigator</h4>
                  <p className="text-sm text-gray-400">Offers guidance on organizational dynamics and relationships</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Industry Historian</h4>
                  <p className="text-sm text-gray-400">Provides context on industry trends and future directions</p>
                </div>
                <div className="bg-purple-900/20 p-4 rounded-lg border border-purple-800/30">
                  <h4 className="font-medium text-purple-300">Personal Development Guide</h4>
                  <p className="text-sm text-gray-400">Focuses on soft skills and work-life integration</p>
                </div>
              </div>
            </TabsContent>
          </div>
        </Tabs>
      </div>
    </section>
  );
}
